name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: ray-di/.github/.github/workflows/continuous-integration.yml@v1
    with:
      old_stable: '["7.2", "7.3", "8.0", "8.2", "8.3"]'
      current_stable: 8.3
